dp/config/routes.rb
Dp::Application.routes.draw do
  resources :cast_drama

  resources :casts

  match 'admins/sign_up' => 'home#index'
 match 'comments/new' => 'comments#new' 
 resources :comments

  get "home/index"

  devise_for :admins
  devise_scope :admin do
    get "admins/sign_out", :to => "devise/sessions#destroy"
    
  end
  
  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
    get "users/sign_out", :to => "devise/sessions#destroy"
  end
  
  root :to => "home#index"
  
  
  match 'cast_drama/new/:drama_id/:cast_id' =>  'cast_drama#new'
  get "cast_drama/show"

  get "cast_drama/new"

  get "cast_drama/edit"

  get "cast_drama/destroy"

  match 'casts' => 'cast#index'
  match 'casts/:id' => 'cast#show'

  get "cast/index"

  get "cast/edit"

  get "cast/destroy"

  get "cast/new"

  get "cast/show"
  match 'dramas/addcast/:drama_id/:cast_name/:cast_id' =>  'dramas#addcast'  
  match 'dramas/addcast/:drama_id/:cast_name' =>  'dramas#addcast'
  match 'dramas/addcast/:drama_id' =>  'dramas#addcast'
  match 'dramas/addcast' =>  'dramas#addcast'
  match 'dramas/like/' => 'dramas#like'
  get "dramas/like"
  resources :dramas do
    member do
      get :picture
    end
  end

end

dp/app/models/cast.rb
class Cast < ActiveRecord::Base
    has_many :drama 
    has_many :cast_drama
end

dp/app/controllers/casts_controller.rb
class CastsController < ApplicationController
  # GET /casts
  # GET /casts.xml
  def index
    @casts = Cast.all.sort_by{|a| a.name.downcase}
    @c = {}
    for i in 0..@casts.length-1
      x = @casts[i].name[0,1].downcase
      if x >= "a" and x <= "z" then 
        if @c[x] == nil then @c[x] = Array.new end
        @c[x] = @c[x] << i
      else 
        if @c["other"]== nil then @c["other"] = Array.new end
        @c["other"] = @c["other"] << i
      end      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @casts }
    end
  end

  # GET /casts/1
  # GET /casts/1.xml
  def show
    @cast = Cast.find(params[:id])
    @cd = CastDrama.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cast }
    end
  end

  # GET /casts/new
  # GET /casts/new.xml
  def new
      @check=true
      if !admin_signed_in?
          @check = false
          redirect_to (:controller => :home, :action => :index)
          return
      end
    @cast = Cast.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cast }
    end
  end

  # GET /casts/1/edit
  def edit
      @check=true
      if !admin_signed_in?
          @check = false
          redirect_to (:controller => :home, :action => :index)
          return
      end
    @cast = Cast.find(params[:id])
  end

  # POST /casts
  # POST /casts.xml
  def create
      @check=true
      if !admin_signed_in?
          @check = false
          redirect_to (:controller => :home, :action => :index)
          return
      end
    @cast = Cast.new(params[:cast])

    respond_to do |format|
      if @cast.save
        format.html { redirect_to(@cast, :notice => 'Cast was successfully created.') }
        format.xml  { render :xml => @cast, :status => :created, :location => @cast }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /casts/1
  # PUT /casts/1.xml
  def update
      @check=true
      if !admin_signed_in?
          @check = false
          redirect_to (:controller => :home, :action => :index)
          return
      end
    @cast = Cast.find(params[:id])

    respond_to do |format|
      if @cast.update_attributes(params[:cast])
        format.html { redirect_to(@cast, :notice => 'Cast was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /casts/1
  # DELETE /casts/1.xml
  def destroy
      @check=true
      if !admin_signed_in?
          @check = false
          redirect_to (:controller => :home, :action => :index)
          return
      end
    @cast = Cast.find(params[:id])
      #delete all related object
      @listFilm = @cast.cast_drama
      @listFilm.each do |@f|
          @f.destroy
      end
    @cast.destroy
    
    respond_to do |format|
      format.html { redirect_to(casts_url) }
      format.xml  { head :ok }
    end
  end
end

dp/app/helpers/casts_helper.rb
module CastsHelper
end

dp/app/views/casts/_form.html.erb
<%= form_for(@cast) do |f| %>
  <% if @cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
      <% @cast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dp/app/views/casts/edit.html.erb
<h1>Editing cast</h1>

<%= render 'form' %>

<%= link_to 'Show', @cast %> |
<%= link_to 'Back', casts_path %>

dp/app/views/casts/index.html.erb
<h1 class = "title" style = "text-align:center; color: #111111; font-size:3em;margin-bottom:30px">Cast List</h1>

<table class = "list" style = "margin:auto;width:30%;height:100%">
  <tr>
  	<th style = "width:100px;background: transparent"></th>
    <th>Name</th>
    <% if admin_signed_in? then %>
    <th></th>
    <th></th>
    <% end %>
  </tr>
	<% arr = ('a'..'z').to_a %>
	<% arr = arr << "other"%>
	<% for i in 0..arr.length-1 %>
		<% if @c[arr[i]] != nil %>
			<tr>
				<th rowspan=<%= @c[arr[i]].length %>>
					<div><%= arr[i].upcase %></div>
				</th>
				<% @c[arr[i]].each do |j| %>
					<% cast = @casts[j]%>
					<td style = "text-transform: capitalize;"	><%= link_to cast.name, cast %></td>
  				  	<% if admin_signed_in? then %>
    					<td><%= link_to 'Edit', edit_cast_path(cast) %></td>
    					<td><%= link_to 'Destroy', cast, :confirm => 'Are you sure?', :method => :delete %></td>
    				<% end %>
    				</tr>
				<% end %>
			 <% end %>
	<% end %>	
</table>
<% if admin_signed_in? then %>
<div style = "font-size:1.5em;margin:10px 300px;"><li> <%= link_to 'New Cast', new_cast_path %> </li> </div>
<% end %>

dp/app/views/casts/new.html.erb
<h1>New cast</h1>

<%= render 'form' %>

<%= link_to 'Back', casts_path %>

dp/app/views/casts/show.html.erb
<div class = "showcast">
<p class = "casttitle"><%= @cast.name %></div>
</p>
    <p class = "listcast_title">List Drama:</p></br>
    <div class = "listcast">
    <% if admin_signed_in? then %>
                    <% listDr =[] %>
                    <% listDrama= @cast.cast_drama.sort_by{|a| a.drama.name.downcase} %>
                    <% listDrama.each do |a| %>
                        <li style = "font-size:1.3em;text-transform: capitalize;"><%= link_to a.drama.name ,a.drama %>
                        <% listDr = listDr + [a.drama] %>
                        <% if admin_signed_in? then %>
                            <%= link_to '⊕', a, :confirm => 'Are you sure?', :method => :delete, :cast_id => @cast.id %>
                        <% end %></li>
                        <br/>
                    <% end %>
                    <% if (Drama.all-listDr).length != 0 then %>
        			<%= form_for @cd  , :url => {:controller => "dramas", :action => "addcast" } do |f| %>
            			<div class="field">
                		<%= f.label :drama_id %>
                		<%= f.collection_select :drama_id, Drama.all-listDr, :id, :name %>
            			</div>
            			<div class="actions">
                		<%= f.hidden_field :cast_id ,:value => @cast.id  %>
                		<%= f.submit "Add Drama" %>
            		</div>
        			<% end %>
        			<% end %>
        			<br/>
        <% else %>
                <% listDrama= @cast.cast_drama.sort_by{|a| a.drama.name.downcase} %>
                <% listDrama.each do |a| %>
                    <% if a.drama!= nil %>
                        <li style = "font-size : 1.3em"> <%= link_to a.drama.name, a.drama %></li>
                        </br>
                    <% end %>
                <% end %>
        <% end %>
        </div>
</div>