dp/config/routes.rb
Dp::Application.routes.draw do
  resources :cast_drama

  resources :casts

  match 'admins/sign_up' => 'home#index'
 match 'comments/new' => 'comments#new' 
 resources :comments

  get "home/index"

  devise_for :admins
  devise_scope :admin do
    get "admins/sign_out", :to => "devise/sessions#destroy"
    
  end
  
  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
    get "users/sign_out", :to => "devise/sessions#destroy"
  end
  
  root :to => "home#index"
  
  
  match 'cast_drama/new/:drama_id/:cast_id' =>  'cast_drama#new'
  get "cast_drama/show"

  get "cast_drama/new"

  get "cast_drama/edit"

  get "cast_drama/destroy"

  match 'casts' => 'cast#index'
  match 'casts/:id' => 'cast#show'

  get "cast/index"

  get "cast/edit"

  get "cast/destroy"

  get "cast/new"

  get "cast/show"
  match 'dramas/addcast/:drama_id/:cast_name/:cast_id' =>  'dramas#addcast'  
  match 'dramas/addcast/:drama_id/:cast_name' =>  'dramas#addcast'
  match 'dramas/addcast/:drama_id' =>  'dramas#addcast'
  match 'dramas/addcast' =>  'dramas#addcast'
  match 'dramas/like/' => 'dramas#like'
  get "dramas/like"
  resources :dramas do
    member do
      get :picture
    end
  end

end

dp/app/models/drama.rb
class Drama < ActiveRecord::Base
	belongs_to :genre
	has_many :cast
    has_many :like
    has_many :user, :through => :like
    has_many :comment
    has_many :cast_drama
    def cast_num
        listCast=self.cast_drama
        return listCast.length
    end 
    def cast_list
        listCast=self.cast_drama
        casts = []
        listCast.each do |a|
            casts= casts+  [a.cast]
        end
        return casts
    end
    def like_num
        listLike=self.like
        return listLike.length
    end 
    def like_list
        listLike=self.like
        users = []
        listLike.each do |a|
            users= users+  [a.user.name]
        end
        return casts
    end
    def is_like(user_id)
        tmp = Like.find(:all, :conditions => "drama_id = #{self.id} and user_id = #{user_id}")
        if tmp.length > 0
            return true
        else
            return false
        end
    end
    def picture_file= (p)
      if p
        self.picture_data = p.read
        self.content_type = p.content_type
      end
  end
end

dp/app/controllers/dramas_controller.rb
class DramasController < ApplicationController
  def addcast
      @check=true
      if !admin_signed_in?
          @check = false
          return
      end
        @cd = CastDrama.new(params[:cast_drama])
        @msg = "Insert unsuccessful"
        if CastDrama.find(:all, :conditions => "drama_id = #{@cd.drama_id} and cast_id = #{@cd.cast_id}").length > 0:
            @msg = "Already exited"
        else 
            if @cd.save
                @msg= "Insert successfull"
            end
        end
        
        respond_to do |format|
            format.html { redirect_to(:back) }
        end
  end
  # GET /dramas
  # GET /dramas.xml
  def index
    @check=true
    if !admin_signed_in?
        @check = false
    end

    @dramas = Drama.all.sort_by{|a| a.name.downcase}
    @d = {}
    for i in 0..@dramas.length-1
      x = @dramas[i].name[0,1].downcase
      if x >= "a" and x <= "z" then 
        if @d[x] == nil then @d[x] = Array.new end
        @d[x] = @d[x] << i
      else 
        if @d["other"]== nil then @d["other"] = Array.new end
        @d["other"] = @d["other"] << i
      end      
    end
    @cd= CastDrama.new
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dramas }
    end
  end
 
  # GET /dramas/1
  # GET /dramas/1.xml
  def show
    @drama = Drama.find(params[:id])
    if @drama.view == nil
        @drama.view =0
    end
    @drama.view =@drama.view + 1
    @drama.save
    @cd= CastDrama.new
    @cmt = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @drama }
    end
  end

  # GET /dramas/new
  # GET /dramas/new.xml
  def new
    @check=true
    if !admin_signed_in?
        @check = false
        redirect_to (:controller => :home, :action => :index)
        return
    end
      
    @drama= Drama.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @drama }
    end
  end

  # GET /dramas/1/edit
  def edit
    @check=true
    if !admin_signed_in?
        @check = false
        redirect_to (:controller => :home, :action => :index)
        return
    end

    @drama = Drama.find(params[:id])
  end

  # POST /dramas
  # POST /dramas.xml
  def create
    @check=true
    if !admin_signed_in?
        @check = false
        redirect_to (:controller => :home, :action => :index)
        return
    end

    @drama = Drama.new(params[:drama])

    respond_to do |format|
      if @drama.save
        format.html { redirect_to(@drama, :notice => 'Drama was successfully created.') }
        format.xml  { render :xml => @drama, :status => :created, :location => @drama }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @drama.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dramas/1
  # PUT /dramas/1.xml
  def update
    @check=true
    if !admin_signed_in?
        @check = false
        redirect_to (:controller => :home, :action => :index)
        return
    end

    @drama = Drama.find(params[:id])
        
    respond_to do |format|
      if @drama.update_attributes(params[:drama])
        format.html { redirect_to(@drama, :notice => 'Drama was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @drama.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dramas/1
  # DELETE /dramas/1.xml
  def destroy
    @check=true
    if !admin_signed_in?
        @check = false
        redirect_to (:controller => :home, :action => :index)
        return
    end

    @drama = Drama.find(params[:id])
      #delete all related object
      @listCast1 = @drama.cast_drama
      @listCast1.each do |@C|
          @C.destroy
      end

    @drama.destroy

    respond_to do |format|
      format.html { redirect_to(dramas_url) }
      format.xml  { head :ok }
    end
  end
  def like
      if !user_signed_in?
          redirect_to (new_user_session_path)
          return
      end
      @id= params[:id]
      @id_u = current_user.id
      @like = Like.new(:user_id => @id_u , :drama_id => @id)
      @drama = Drama.find(@id)
      @msg = "Insert unsuccessful"
      tmp = Like.find(:all, :conditions => "drama_id = #{@id} and user_id = #{@id_u}")
      if tmp.length > 0
            @msg = "Already exited"
            tmp[0].destroy
      else 
            if @like.save
                @msg= "Insert successfull"
            else
                @msg=  "Cannot insert"
            end
      end
      #redirect_to (:controller => :home, :action => :index)
      respond_to do |format|
        format.html {redirect_to (@drama)}
        format.js
      end 
  end
  def picture
    @drama = Drama.find(params[:id])
    send_data(@drama.picture_data, :type => @drama.content_type)
  end
end

dp/app/helpers/dramas_helper.rb
module DramasHelper
        
end

dp/app/views/dramas/_comment_form.html.erb
  		<% if @drama.comment.length > 0 then %>	
  			<% comments = @drama.comment %>
 	 		<% cmtlength = comments.length %>
  				<% for i in 0..cmtlength-1 do %>
  		  		<% cmt = comments[cmtlength-1-i]%>
        		  <p class = "user_email">
        	  		#<%= cmtlength-i %>. 
        	  			<% if user_signed_in? && cmt.user_id == current_user.id then %>
        	  		You
        	  		<% else%>
        	  		<%= User.find(cmt.user_id).email %>
        	  		<% end %> posted
        	  		<% if (Time.now-cmt.created_at).to_i <= 82800 then %>
        	  		<%= time_ago_in_words(cmt.created_at) %> ago
        	  		<% else %>
        	  		at <%= cmt.created_at%>
        	  	<% end %>
        	  	<% if user_signed_in? && cmt.user_id == current_user.id then %>
                            <%= link_to 'Delete', cmt, :confirm => 'Are you sure to delete this comment?', :method => :delete %>
                    <% end %>
        	  	</p>
        	  	<p class = "user_comment">
        	  		<%= cmt.comment %>
        	  	</p>
      		<% end %>
 	<% end %>	

dp/app/views/dramas/_form.html.erb
<%= form_for(@drama, :html => {:multipart => true}) do |f| %>
  <% if @drama.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drama.errors.count, "error") %> prohibited this drama from being saved:</h2>
      <ul>
      <% @drama.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture_file %><br />
    <%= f.file_field :picture_file %>
  </div>
  <!-- <div class="field">
    <%= f.label:Genre %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div> -->  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :episode %><br />
    <%= f.text_field :episode %>
  </div>
    <div class="field">
    <%= f.label :"Number views" %><br />
    <%= f.text_field :view %>
  </div>
  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>

dp/app/views/dramas/_like_form.html.erb
<% if user_signed_in? then %>
<% form_for @drama, :remote => :true, :url => {:controller => 'dramas' , :action => 'like' , :id => @drama, :method => :post} do |f| %>
	<% if @drama.is_like(current_user.id) %>
      <%= f.submit '-1', :class => 'plusone_bttn', :id => 'bttn' %>
      <% else %>
      <%= f.submit '+1', :class => 'plusone_bttn', :id => 'bttn' %>
    <% end %>
<% end %>
<% end %>

dp/app/views/dramas/addcast.html.erb
    <p><%= @msg %> <%= @cd.cast_id %> to <%= @cd.drama_id %></p>

dp/app/views/dramas/edit.html.erb
<h1>Editing drama</h1>

<%= render 'form' %>

<%= link_to 'Show', @drama %> |
<%= link_to 'Back', dramas_path %>

dp/app/views/dramas/index.html.erb
<h1 class = "title" style = "text-align:center; color: #111111; font-size:3em;margin-bottom:30px">Drama List</h1>
<div = "dramalisting">
<table class = "list" style = "margin:auto;width:60%;height:100%">
  <tr>
  	<th style = "background: transparent"></th>
    <th>Name</th>
<!--     <th>Genre</th> -->    <!-- <th>Cast</th>
    <th>Info</th> -->
    <th>Rating</th>
    <th>Episode</th>
    <th>Like</th>
    <th>View</th>
    <th>Comment</th>
    <% if admin_signed_in? then %>
    <th></th>
    <th></th>
    <% end %>
  </tr>

	<% arr = ('a'..'z').to_a %>
	<% arr = arr << "other"%>
	<% for i in 0..arr.length-1 %>
		<% if @d[arr[i]] != nil %>
			<tr>
				<th rowspan=<%= @d[arr[i]].length%>>
					<div><%= arr[i].upcase %></div>
				</th>
				<% @d[arr[i]].each do |j| %>
				<% drama = @dramas[j]%>
				<td style = "text-transform: capitalize;"><%= link_to drama.name, drama %></td>
    			
    			<!-- <td><% listCast=drama.cast_drama %>
    			<% listCast.each do |a| %>
            		<%= link_to a.cast.name ,a.cast %>
            		<% if admin_signed_in? then %>
            			<%= link_to '⊕', a, :confirm => 'Are you sure?', :method => :delete %>
            		<% end %>
            		<br/>
        		<% end %>
        		</br>
        
       			 <% if admin_signed_in? then %>
        			<% @cd.drama_id=drama.id %>
        			<%= form_for @cd  , :url => { :action => "addcast" } do |f| %>
            			<div class="field">
                		<%= f.label :cast_id %>
                		<%= f.collection_select :cast_id, Cast.all - drama.cast_list, :id, :name %>
            			</div>
            			<div class="actions">
                		<%= f.hidden_field :drama_id ,:value => drama.id  %>
                		<%= f.submit "Add Cast" %>
            		</div>
        			<% end %>
        			<br/>
        		<% end %>
				</td>	 -->    
<!--     			<td><%= drama.info %></td> -->
    			<td><%= drama.rating %></td>
    			<td><%= drama.episode %></td>
    			<td><%= drama.like_num %></td>
    			<td><%= drama.view %></td>
    			<td><%= drama.comment.length %></td>
    			<% if admin_signed_in? then %>
    				<td><%= link_to 'Edit', edit_drama_path(drama) %></td>
    				<td><%= link_to 'Destroy', drama, :confirm => 'Are you sure?', :method => :delete %></td>
    			<% end %>
  			</tr>
  			<% end %>
			<% end %>
			<% end %>

</table>
<br/>

<% if admin_signed_in? then %>
<div style = "font-size:1.5em;margin:10px 200px;"><li> <%= link_to 'New Drama', new_drama_path %> </li> </div>

<% end %>
</div>

dp/app/views/dramas/like.html.erb
<%= @drama.name %>

dp/app/views/dramas/like.js.erb
$("like_number").update(" <%= @drama.like_num %> ")
$("bttn").replace("")
$("plusone_button").update("<%=  escape_javascript(render ('dramas/like_form')) %>");

dp/app/views/dramas/new.html.erb
<h1>New drama</h1>

<%= render 'form' %>

<%= link_to 'Back', dramas_path %>

dp/app/views/dramas/show.html.erb
<div class="showdrama">
  <p class = "dramatitle">
      <%= @drama.name %>
    </p>
   <div class = "drama_border"> 
  <div class = "poster">
  		<% if @drama.picture_data == nil %>
  		<%= image_tag 'no_poster.jpg', :height => '100%'%>
  		<% else %>
  		<%= image_tag picture_drama_path(@drama), :height => '100%' %>
  		<% end %>
    </div>
    
  <div class = "dramainfo"> 
    <p>
      <strong>Rating:</strong>
      <%= @drama.rating %>
    </p>
 
    <p>
      <strong>Episode:</strong>
      <%= @drama.episode %>
    </p>
    <p>
      <strong>View:</strong>
      <%= @drama.view %>
    </p>
    <p>
      <strong>Like:</strong>
      <span id = "like_number"> <%= @drama.like_num %></span>
    </p>
    <p id = "plusone_button"> <%= render 'like_form' %></p>
  </div>
  </div>
  <p class = "title">Synopsis<p>
  <div class = "dramasynopsis">
    <p><%= @drama.info %>
    </p>
  </div>
  <p class = "title">Cast</p>  
	<div class = "dramacast">
     
        <% if admin_signed_in? then %>
                    <% listCast=@drama.cast_drama.sort_by{|a| a.cast.name} %>
                    <% listCast.each do |a| %>
                        <li style = "font-size:1.2em;line-height:2em;"><%= link_to a.cast.name ,a.cast %>
                        <% if admin_signed_in? then %>
                            <%= link_to '⊕', a, :confirm => 'Are you sure?', :method => :delete %>
                        <% end %></li>
                    <% end %>
                    
        			
        			<%= form_for @cd  , :url => { :action => "addcast" } do |f| %>
        				<br/>
            			<div class="field">
                		<%= f.label :cast_id %>
                		<%= f.collection_select :cast_id, Cast.all - @drama.cast_list, :id, :name %>
            			</div>
            			<div class="actions">
                		<%= f.hidden_field :drama_id ,:value => @drama.id  %>
                		<%= f.submit "Add Cast" %>
            		</div>
        			<% end %>
        			<br/>
        <% else %>
            <% listCast=@drama.cast_drama.sort_by{|a| a.cast.name} %>
                    <% listCast.each do |a| %>
                        <li style = "font-size:1.2em;line-height:2em;"><%= link_to a.cast.name ,a.cast %></li>
                    <% end %>
        <% end %>
 	 </div>  
	
	<p class = "title">Write your comment</p>  
	<div class = "postcomment">
    <%= form_for @cmt, :remote => :true, :url => {:controller => "comments" , :action => "new" , :method => :post} do |f| %>
            <div class="field">
                <%= f.text_area :comment, :class => "textarea_comment", :id => "text_area_comment" %>
            </div>
            <div class="actions">
                <%= f.hidden_field :drama_id ,:value => @drama.id  %>
                <% if user_signed_in? %>
                	<%= f.hidden_field :user_id ,:value => current_user.id  %>
                <% elsif admin_signed_in? %>
                	<%= f.hidden_field :admin_id ,:value => current_admin.id  %>
                <% end %>
                <%= f.submit "Post Comment", :class => "post_button" %>
            </div>
        <% end %>
	</div>
	<p class = "title" id = "comment_number"> <%= @drama.comment.length %> Comments </p>
	<div class = "comments" id = "all_comments" > <%= render 'comment_form' %> </div>
</div>