dp/config/routes.rb
Dp::Application.routes.draw do
  resources :cast_drama

  resources :casts

  match 'admins/sign_up' => 'home#index'
 match 'comments/new' => 'comments#new' 
 resources :comments

  get "home/index"

  devise_for :admins
  devise_scope :admin do
    get "admins/sign_out", :to => "devise/sessions#destroy"
    
  end
  
  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
    get "users/sign_out", :to => "devise/sessions#destroy"
  end
  
  root :to => "home#index"
  
  
  match 'cast_drama/new/:drama_id/:cast_id' =>  'cast_drama#new'
  get "cast_drama/show"

  get "cast_drama/new"

  get "cast_drama/edit"

  get "cast_drama/destroy"

  match 'casts' => 'cast#index'
  match 'casts/:id' => 'cast#show'

  get "cast/index"

  get "cast/edit"

  get "cast/destroy"

  get "cast/new"

  get "cast/show"
  match 'dramas/addcast/:drama_id/:cast_name/:cast_id' =>  'dramas#addcast'  
  match 'dramas/addcast/:drama_id/:cast_name' =>  'dramas#addcast'
  match 'dramas/addcast/:drama_id' =>  'dramas#addcast'
  match 'dramas/addcast' =>  'dramas#addcast'
  match 'dramas/like/' => 'dramas#like'
  get "dramas/like"
  resources :dramas do
    member do
      get :picture
    end
  end

end

dp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
    <div id="header">
      <h1><a href="/">Drama Comments</a></h1>
      <div>
         <ul class="hmenu">
      <% if user_signed_in? then %>
      			<p>Hi, <%= current_user.email %></p>
      			<li><%= link_to('Edit registration', edit_user_registration_path) %></li>
      			<li style = "color:white">|</li>
  				<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
  				<% if !current_page?(edit_user_registration_path) %>
  				<p>
				<li><%= link_to('Home', :controller => 'home' , :action => :index) %></li>
				<li style = "color:white">|</li>
				<li><%= link_to('List Dramas', :controller => 'dramas' , :action => :index) %></li>
				<li style = "color:white">|</li>
				<li><%= link_to('List Casts', :controller => 'casts' , :action => :index) %></li>
				</p>
				<% end %>
		<% elsif admin_signed_in? then%>	
      			<p>Hi, <%= current_admin.email %></p>
      			<li><%= link_to('Edit registration', edit_admin_registration_path) %></li>
      			<li style = "color:white">|</li>
  				<li><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></li>
  				<% if !current_page?(edit_admin_registration_path) %>
  				<p>
				<li><%= link_to('Home', :controller => 'home' , :action => :index) %></li>
				<li style = "color:white">|</li>
				<li><%= link_to('List Dramas', :controller => 'dramas' , :action => :index) %></li>
				<li style = "color:white">|</li>
				<li><%= link_to('List Casts', :controller => 'casts' , :action => :index) %></li>
				</p>
				<% end %>
		<% end %>
		</ul>
		</div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div id="main">
        <%= yield %>
      </div>
      <div id="footer"
            <p><center>Copyright &copy; HUSTMAN @ KEIO UNIVERSITY 2012</center></p>
      </div>
    </div>    
  </div>
</body>
</html>